name: Go
on:
  pull_request:
    paths:
    - '**.go'

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run gofmt
        run: gofmt -l .
